name: Lint with golangci-lint

on:
  push:
    branches:
      - main

jobs:
  golangci:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./src
          args: --timeout=3m --exclude-files wire_gen.go